version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    command: /bin/bash -c  "composer install && apachectl -D FOREGROUND"
    
    networks:
      - laravel

  db:
    image: mysql:8.0.31
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
